title: "Nico's Portfolio"
description: "Work at the intersection of ergonomics, aesthetic, and function."
baseurl: ""
url: "https://nbonnetm.github.io"

# Collections — tells Jekyll to process the _projects folder
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
